name: Manual APK Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Make Gradle executable
      run: chmod +x gradlew
    
    - name: Build APK
      run: ./gradlew assemble${{ github.event.inputs.build_type == 'debug' && 'Debug' || 'Release' }}
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Lidl-refill-${{ github.event.inputs.build_type }}
        path: app/build/outputs/apk/${{ github.event.inputs.build_type }}/app-${{ github.event.inputs.build_type }}.apk
